/**
 * Netlify Function: POST /api/manage (ACP)
 * Generated by Echelon installer. CommonJS for Netlify.
 */

const { createManageRouter, iamPack, webhooksPack, settingsPack } = require('agentic-control-plane-kit/cjs');
const { createAdapters } = require('../../control_plane/adapters');
const bindings = require('../../controlplane.bindings.json');
const domainPack = require('../../control_plane/domain-pack');

const router = createManageRouter({
  ...createAdapters(),
  bindings,
  packs: [iamPack, webhooksPack, settingsPack, domainPack]
});

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, X-API-Key',
  'Content-Type': 'application/json'
};

exports.handler = async function (event, context) {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: CORS_HEADERS, body: '' };
  }
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Method not allowed' })
    };
  }

  let body;
  try {
    body = typeof event.body === 'string' ? JSON.parse(event.body) : event.body || {};
  } catch (e) {
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: JSON.stringify({ ok: false, error: 'Invalid JSON', code: 'VALIDATION_ERROR' })
    };
  }

  const meta = {
    request: event,
    ipAddress: event.headers['x-forwarded-for'] || event.headers['client-ip'] || 'unknown',
    userAgent: event.headers['user-agent'] || 'unknown'
  };

  try {
    const response = await router(body, meta);
    const statusCode = response.ok ? 200 : (response.code === 'INVALID_API_KEY' ? 401 : response.code === 'SCOPE_DENIED' ? 403 : response.code === 'NOT_FOUND' ? 404 : response.code === 'RATE_LIMITED' ? 429 : 500);
    return {
      statusCode,
      headers: CORS_HEADERS,
      body: JSON.stringify(response)
    };
  } catch (err) {
    return {
      statusCode: 500,
      headers: CORS_HEADERS,
      body: JSON.stringify({ ok: false, error: String(err && err.message || err), code: 'INTERNAL_ERROR' })
    };
  }
};
