/**
 * Netlify Function: POST /api/manage (ACP)
 * Generated by Echelon installer. CommonJS for Netlify.
 */

const fs = require('fs');
const path = require('path');
const { createAdapters } = require('../../control_plane/adapters');
const domainPack = require('../../control_plane/domain-pack');

let router = null;
let routerInitError = null;

function loadBindings() {
  const bindingsPath = path.resolve(__dirname, '../../controlplane.bindings.json');

  if (!fs.existsSync(bindingsPath)) {
    return {};
  }

  const file = fs.readFileSync(bindingsPath, 'utf8');
  return JSON.parse(file);
}

function getRouter() {
  if (router || routerInitError) {
    return { router, routerInitError };
  }

  try {
    // Use non-static require so bundlers don't fail hard when ACP kit isn't installed.
    const req = eval('require');
    const {
      createManageRouter,
      iamPack,
      webhooksPack,
      settingsPack,
    } = req('agentic-control-plane-kit/cjs');

    const bindings = loadBindings();

    router = createManageRouter({
      ...createAdapters(),
      bindings,
      packs: [iamPack, webhooksPack, settingsPack, domainPack]
    });
  } catch (err) {
    routerInitError = err;
  }

  return { router, routerInitError };
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, X-API-Key',
  'Content-Type': 'application/json'
};

exports.handler = async function (event, context) {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: CORS_HEADERS, body: '' };
  }
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Method not allowed' })
    };
  }

  const { router: activeRouter, routerInitError: initErr } = getRouter();
  if (!activeRouter) {
    return {
      statusCode: 503,
      headers: CORS_HEADERS,
      body: JSON.stringify({
        ok: false,
        error: `Control plane dependency unavailable: ${String(initErr && initErr.message || initErr)}`,
        code: 'DEPENDENCY_UNAVAILABLE'
      })
    };
  }

  let body;
  try {
    body = typeof event.body === 'string' ? JSON.parse(event.body) : event.body || {};
  } catch (e) {
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: JSON.stringify({ ok: false, error: 'Invalid JSON', code: 'VALIDATION_ERROR' })
    };
  }

  const meta = {
    request: event,
    ipAddress: event.headers['x-forwarded-for'] || event.headers['client-ip'] || 'unknown',
    userAgent: event.headers['user-agent'] || 'unknown'
  };

  try {
    const response = await activeRouter(body, meta);
    const statusCode = response.ok ? 200 : (response.code === 'INVALID_API_KEY' ? 401 : response.code === 'SCOPE_DENIED' ? 403 : response.code === 'NOT_FOUND' ? 404 : response.code === 'RATE_LIMITED' ? 429 : 500);
    return {
      statusCode,
      headers: CORS_HEADERS,
      body: JSON.stringify(response)
    };
  } catch (err) {
    return {
      statusCode: 500,
      headers: CORS_HEADERS,
      body: JSON.stringify({ ok: false, error: String(err && err.message || err), code: 'INTERNAL_ERROR' })
    };
  }
};
