/**
 * Supabase adapters for Netlify (CommonJS)
 * Generated by Echelon installer. Uses env: VITE_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY.
 */

const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;

function getSupabase() {
  if (!supabase) throw new Error('Missing VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
  return supabase;
}

class SupabaseDbAdapter {
  async query(sql, params) {
    const { data, error } = await getSupabase().rpc('execute_sql', { sql, params: params || [] });
    if (error) throw error;
    return data || [];
  }
  async queryOne(sql, params) {
    const rows = await this.query(sql, params);
    return rows[0] || null;
  }
  async execute(sql, params) {
    const { error } = await getSupabase().rpc('execute_sql', { sql, params: params || [] });
    if (error) throw error;
    return 1;
  }
  async getTenantFromApiKey(apiKeyId) {
    const { data } = await getSupabase().from('api_keys').select('org_id').eq('id', apiKeyId).single();
    return data ? (data.org_id || data.tenant_id) : null;
  }
}

class SupabaseAuditAdapter {
  async log(entry) {
    await getSupabase().from('audit_log').insert(entry);
  }
}

class SupabaseIdempotencyAdapter {
  async getReplay(tenantId, action, idempotencyKey) {
    const { data } = await getSupabase().from('idempotency_cache').select('response').eq('tenant_id', tenantId).eq('action', action).eq('idempotency_key', idempotencyKey).single();
    return data ? data.response : null;
  }
  async storeReplay(tenantId, action, idempotencyKey, response) {
    await getSupabase().from('idempotency_cache').upsert({ tenant_id: tenantId, action, idempotency_key: idempotencyKey, response }, { onConflict: 'tenant_id,action,idempotency_key' });
  }
}

class SupabaseRateLimitAdapter {
  async check(apiKeyId, action, limit) {
    const key = `ratelimit:${apiKeyId}:${action}`;
    const { data } = await getSupabase().from('rate_limit_bucket').select('count').eq('key', key).single();
    const count = (data && data.count) || 0;
    const allowed = count < limit;
    if (allowed) await getSupabase().from('rate_limit_bucket').upsert({ key, count: count + 1, updated_at: new Date().toISOString() }, { onConflict: 'key' });
    return { allowed, limit, remaining: Math.max(0, limit - count - 1) };
  }
}

class SupabaseCeilingsAdapter {
  async check(action, params, tenantId) {}
  async getUsage(ceilingName, tenantId, period) { return null; }
}

function createAdapters() {
  return {
    dbAdapter: new SupabaseDbAdapter(),
    auditAdapter: new SupabaseAuditAdapter(),
    idempotencyAdapter: new SupabaseIdempotencyAdapter(),
    rateLimitAdapter: new SupabaseRateLimitAdapter(),
    ceilingsAdapter: new SupabaseCeilingsAdapter()
  };
}

module.exports = { createAdapters };
